# clip-06-10.jl

Load Julia packages (libraries) needed  for the snippets in chapter 0

In [1]:
using StatisticalRethinking, Optim
gr(size=(600,300));

### snippet 3.2

In [2]:
p_grid = range(0, step=0.001, stop=1)
prior = ones(length(p_grid))
likelihood = [pdf(Binomial(9, p), 6) for p in p_grid]
posterior = likelihood .* prior
posterior = posterior / sum(posterior)

1001-element Array{Float64,1}:
 0.0                   
 8.374825191541396e-19 
 5.3438084689545866e-17
 6.068652771820298e-16 
 3.3995172504952293e-15
 1.2929107734284453e-14
 3.84898254467861e-14  
 9.67643250408127e-14  
 2.149583027999239e-13 
 4.3446551042066853e-13
 ⋮                     
 4.0984465911760347e-7 
 2.7622876204248817e-7 
 1.7500535729671214e-7 
 1.01889113481695e-7   
 5.248259379294106e-8  
 2.22748095801673e-8   
 6.639762126365043e-9  
 8.349725832067523e-10 
 0.0                   

### snippet 3.3
Draw 10000 samples from this posterior distribution

In [3]:
N = 10000
samples = sample(p_grid, Weights(posterior), N);

In StatisticalRethinkingJulia samples will always be stored
in an MCMCChains.Chains object.

In [4]:
chn = MCMCChains.Chains(reshape(samples, N, 1, 1), ["toss"]);

Describe the chain

In [5]:
describe(chn)

2-element Array{ChainDataFrame,1}

Summary Statistics

│ Row │ parameters │ mean     │ std     │ naive_se  │ mcse       │ ess     │
│     │ Symbol     │ Float64  │ Float64 │ Float64   │ Float64    │ Any     │
├─────┼────────────┼──────────┼─────────┼───────────┼────────────┼─────────┤
│ 1   │ toss       │ 0.636756 │ 0.13862 │ 0.0013862 │ 0.00148087 │ 10000.0 │

Quantiles

│ Row │ parameters │ 2.5%    │ 25.0%   │ 50.0%   │ 75.0%   │ 97.5%   │
│     │ Symbol     │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │
├─────┼────────────┼─────────┼─────────┼─────────┼─────────┼─────────┤
│ 1   │ toss       │ 0.353   │ 0.541   │ 0.643   │ 0.741   │ 0.881   │


### snippet 3.6

In [6]:
v = 0.0
for i in 1:length(p_grid)
  global v
  if p_grid[i] < 0.5
    v += posterior[i]
  end
end
v

0.17105550781217763

### snippet 3.7

In [7]:
mapreduce(p -> p < 0.5 ? 1 : 0, +, samples) / N   |> display

### snippet 3.8

In [8]:
mapreduce(p -> (p > 0.5 && p < 0.75) ? 1 : 0, +, samples) / N   |> display

### snippet 3.9

In [9]:
quantile(samples, 0.8)

0.763

### snippet 3.10

In [10]:
quantile(samples, [0.1, 0.9])

2-element Array{Float64,1}:
 0.4519000000000001
 0.813             

End of `03/clip-06-10.jl`#-
*This notebook was generated using [Literate.jl](https://github.com/fredrikekre/Literate.jl).*